apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-sender
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: msg-sender
        image: registry.chatalk.fr/msg_sender:master
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          value: nats://nats:4222
        - name: NATS_CLUSTER_ID
          value: stan
        - name: DB_HOST
          value: chatalk-postgres-cluster
        - name: DB_DB
          value: chatalk
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: chatalk.chatalk-postgres-cluster.credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: chatalk.chatalk-postgres-cluster.credentials
              key: password
        - name: DB_MODE
          value: require
