apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-sender
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: msg-sender
        image: registry.chatalk.fr/msg_sender:master
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          value: nats://nats:4222
        - name: NATS_CLUSTER_ID
          value: stan
        - name: DB_HOST
          value: db
        - name: DB_DB
          value: chatalk
        - name: DB_USER
          value: chatalk
        - name: DB_PASS
          value: chatalk
        - name: DB_MODE
          value: disable
