apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  template:
    spec:
      containers:
      - name: db-migrations
        image: registry.chatalk.fr/db-migrations:master
        args:
        - -database=postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_DB)?sslmode=$(DB_MODE)
        - up
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_HOST
        - name: DB_DB
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_PASS
        - name: DB_MODE
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_MODE
      restartPolicy: Never
  backoffLimit: 5
