apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  template:
    spec:
      containers:
      - name: db-migrations
        image: registry.chatalk.fr/db-migrations:master
        args:
        - -database=postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST)/$(DB_DB)?sslmode=$(DB_MODE)
        - up
        env:
        - name: DB_HOST
          value: chatalk-postgres-cluster
        - name: DB_DB
          value: chatalk
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: chatalk.chatalk-postgres-cluster.credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: chatalk.chatalk-postgres-cluster.credentials
              key: password
        - name: DB_MODE
          value: require
      restartPolicy: Never
  backoffLimit: 5
