apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: entrypoint
        image: registry.chatalk.fr/entrypoint:master
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: NATS_CLUSTER_ID
