apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: entrypoint
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: entrypoint
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
