config:
  target: "wss://ws.chatalk.fr"
  phases:
  - duration: 60  # Test for 60 seconds
    arrivalRate: 10 # Every second, add 10 users
    rampTo: 250 # And ramp it up to 100 users in total over the 60s period
    name: "Ramping up the load"
  - duration: 120 # Then resume the load test for 120s
    arrivalRate: 250 # With those 100 users we ramped up to in the first phase
    rampTo: 250 # And keep it steady at 100 users
    name: "Pushing a constant load"
  - duration: 500 # Then resume the load test for 120s
    arrivalRate: 50 # With those 100 users we ramped up to in the first phase
    rampTo: 800 # And keep it steady at 100 users
    name: "Power"
scenarios:
- engine: "ws"
  flow:
  - send: '{"action":"ping","payload":{}}'
  - think: 5
  - send: '{"action":"ping","payload":{}}'
  - think: 10
