apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy
spec:
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: public
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
