apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
      nats_cluster: nats
  endpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stan
spec:
  selector:
    matchLabels:
      app: stan-svc
  endpoints:
  - port: metrics
