apiVersion: v1
kind: Service
metadata:
  name: stan-svc
  labels:
    app: stan-svc
spec:
  selector:
    app: nats-streaming
    stan_cluster: stan
  ports:
    - name: metrics
      port: 7777
      targetPort: metrics
