version: '3'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=chatalk
      - POSTGRES_PASSWORD=chatalk

  db-migrations:
    build: db-migrations/
    restart: "no"
    command:
      - -database=postgres://chatalk:chatalk@db/chatalk?sslmode=disable
      - up
    depends_on:
      - db

  bus:
    image: nats-streaming
    command:
      - --cluster_id=chatalk
      - --http_port=8222
    ports:
      - 4222:4222
      - 8222:8222

  entrypoint:
    build:
      context: .
      args:
        service: entrypoint
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
    ports:
      - 42042:42042

  register:
    build:
      context: .
      args:
        service: register
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
      - DB_HOST=db
      - DB_DB=chatalk
      - DB_USER=chatalk
      - DB_PASS=chatalk
      - DB_MODE=disable

  ping:
    build:
      context: .
      args:
        service: ping
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk

  conv_creation:
    build:
      context: .
      args:
        service: conv_creation
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
      - DB_HOST=db
      - DB_DB=chatalk
      - DB_USER=chatalk
      - DB_PASS=chatalk
      - DB_MODE=disable

  conv_manag:
    build:
      context: .
      args:
        service: conv_manag
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
      - DB_HOST=db
      - DB_DB=chatalk
      - DB_USER=chatalk
      - DB_PASS=chatalk
      - DB_MODE=disable

  conv-sub:
    build:
      context: .
      args:
        service: conv-sub
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
      - DB_HOST=db
      - DB_DB=chatalk
      - DB_USER=chatalk
      - DB_PASS=chatalk
      - DB_MODE=disable

  login:
    build:
      context: .
      args:
        service: login
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
      - DB_HOST=db
      - DB_DB=chatalk
      - DB_USER=chatalk
      - DB_PASS=chatalk
      - DB_MODE=disable
      - JWT_SECRET=ieRe9Pohyah3uacheJaeTho8

  send-info:
    build:
      context: .
      args:
        service: send-info
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
      - DB_HOST=db
      - DB_DB=chatalk
      - DB_USER=chatalk
      - DB_PASS=chatalk
      - DB_MODE=disable

  msg_sender:
    build:
      context: .
      args:
        service: msg_sender
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
      - DB_HOST=db
      - DB_DB=chatalk
      - DB_USER=chatalk
      - DB_PASS=chatalk
      - DB_MODE=disable

  user-manag:
    build:
      context: .
      args:
        service: user-manag
    depends_on:
      - bus
      - db-migrations
    environment:
      - NATS_URL=nats://bus:4222
      - NATS_CLUSTER_ID=chatalk
      - DB_HOST=db
      - DB_DB=chatalk
      - DB_USER=chatalk
      - DB_PASS=chatalk
      - DB_MODE=disable

  fake-ui:
    build: fake-ui/
    ports:
      - 1234:80

  ui:
    build: ../ui/
    ports:
      - 4321:80
    environment:
      - BACKEND_URL=ws://localhost:42042
