---
# Source: kubefed/charts/controllermanager/templates/webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-federation-system
  name: kubefed-admission-webhook-serving-cert
type: kubernetes.io/tls
stringData:
  tls.crt: "-----BEGIN CERTIFICATE-----\nMIIDiTCCAnGgAwIBAgIQLzVDEKKwS6i8ZWw2inhcljANBgkqhkiG9w0BAQsFADAn\nMSUwIwYDVQQDExxrdWJlZmVkLWFkbWlzc2lvbi13ZWJob29rLWNhMB4XDTE5MTIw\nNzE1NDM1NloXDTI5MTIwNDE1NDM1NlowJDEiMCAGA1UEAxMZa3ViZWZlZC1hZG1p\nc3Npb24td2ViaG9vazCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJF\ngmEU8zEePWPzEuWkLnVczp0KdIA9nfcj1K6hyTYOXyBeMdZi0XyNEarfQqbFHWZT\nGwXrCViZR9b1B2VlMQ8UzbcC95tKMCTEleGUOueyMQ9lYRGoF8CwTXzo88lntZ6e\nVxUsTYUfJ0xaHAfW7MCK8i1nuVnWpKZLGHlB28V8snjAYCy9c1uf3Q4LmhKmNb74\nCQyUPBiQ5mE1jKPiSJoDJ/ezzzb6Nnf+4goUfvBBHV5HE2gQMY6dVmfU0E88E6TF\nAHX7Hx0y7i63Ml05G7egZ5I/+xwz1eNVHVWN3YL8vP82aTm42rSQFLR4K/IA+5ry\nn4+bB8v+kUQEzipAD+UCAwEAAaOBszCBsDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0l\nBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwcQYDVR0RBGow\naIIwa3ViZWZlZC1hZG1pc3Npb24td2ViaG9vay5rdWJlLWZlZGVyYXRpb24tc3lz\ndGVtgjRrdWJlZmVkLWFkbWlzc2lvbi13ZWJob29rLmt1YmUtZmVkZXJhdGlvbi1z\neXN0ZW0uc3ZjMA0GCSqGSIb3DQEBCwUAA4IBAQAYVSkqrV4T8JJJqnkv62GkmL7I\nbsBSRLecfObREl1yjQR1IlI0N/fku5WiVFC/1qedmUcn1V5gUZ+xymjr6/cN3Qq0\nHejHZPyK0I6Yjo7U9ohKIWCAXmvh46qQIetH1maDyqf20OSZeXYfwBcdhrhSQTVw\n1Lzof/RcXDIDJzywr2uxyRcU1c8y2w/8/Nh1MKJAUE5+44kqDFaFt5Bloo5cIPUw\nHhBrUeO+wMO+ylUau8E7bntr3LT4yziaiJ9z9/w2OCuvpeI6gVOfPEgIyLSDNgnp\nwFU3rTWr0JqZjQB7PvkCu9TBBsdT/7cK1//OG8DdmXGt8zVvsS5wzo9a2LSs\n-----END CERTIFICATE-----\n"
  tls.key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpQIBAAKCAQEAskWCYRTzMR49Y/MS5aQudVzOnQp0gD2d9yPUrqHJNg5fIF4x\n1mLRfI0Rqt9CpsUdZlMbBesJWJlH1vUHZWUxDxTNtwL3m0owJMSV4ZQ657IxD2Vh\nEagXwLBNfOjzyWe1np5XFSxNhR8nTFocB9bswIryLWe5WdakpksYeUHbxXyyeMBg\nLL1zW5/dDguaEqY1vvgJDJQ8GJDmYTWMo+JImgMn97PPNvo2d/7iChR+8EEdXkcT\naBAxjp1WZ9TQTzwTpMUAdfsfHTLuLrcyXTkbt6Bnkj/7HDPV41UdVY3dgvy8/zZp\nObjatJAUtHgr8gD7mvKfj5sHy/6RRATOKkAP5QIDAQABAoIBAQCrECYO0FKYVGMm\nUK5Wa5glCDw+1zR5hibZaqmANUDlvR6s6ZY7GTHZqWhFpdzIOKeAc8ifgizCtrsH\n2rIRKuvLg/PuZEuC2MqfzX/hKSLpB8Up9+cQUVMRlFuWu9aK8hiGL3xylcOBNSa5\njlINd8BQ9kNzLG/gdCYkaDUAziB8PBM/CrWVh9k1ps8Dsn6dbZ4uN/vhGy65RROQ\n0AO9SJzt6RCGcTUv3mLpQi7I8IaAOLrJpOh6oUG8c0Wcbw19ajeG73XWXVyB0kIh\nryWc73z7Tjhd1KQudT4Je53W7mtOtm5MHjenP2oa3Q49coffRGzb9uKb+oeBW7il\nMAz5P/YBAoGBAMMm7y1ZO0ofTtLodYVrtI2De1LTVfUTqG0fDJnGCPSpQIuGFS8l\n8VQVA7CMWiBM+Kiy2BwgncnUNPF89XITj2QRYW2rO++jgAFbtB8YoMK7OyaM39tO\n0xbREWaRTUZpNfom7OP+lPOVmGZDFUSFbfMruau+U/NqgdwNOckUEktlAoGBAOnb\nKnsPu+wxKI+fPFvumeiiC8qqsSTJORJtM8Eg4I+SRvBJs9f/ujiguw/WXkdEt7G3\nw9/Bf54UGXxWg4oZG0gJ3pTdXrEfDCDrH0fUZ1PTMsHTJFDqfZHUZNhFZa2i1Tyf\n3z23rYGkoaDkrRz/IDMMzc6Jp9HvBxgwB1P5K6qBAoGBALNBxTtLlrl8TqRO4PyA\nNaYzmwk2lON8fh5WAfYSQVGzUlWXAUiAus84Sl5WXccDzPjw5q/XifjFkygrVy3F\nJ9aMXIknW/PApKkaujZCIhEdeLTtfAbvvdhcjHZBi9DcfbddIAZBaELjK8zrW9LI\nGXnftTo7ptOWBtjB0U2RwUg9AoGAQj0M3EyJmw4VghDFZPjBaW40ztPoVxYT7081\nIJfyY1g4dak6oozRr2Z/da3viFpDebgmaAOD5T+mNFzA52XTH2WEQUAuqRa1NcHD\nW3IjTk/9CX+Hws+Yf6zcX5HQig0cPw69idqz74u1KEB9dEAjW7JdvQmqmkENDmHU\nQYnLP4ECgYEAjQStpxRVix7awpyitb44OhVmNhtLrC8gU60Q0oEjq0zGl7YE0oHm\nYAdQKEqFA7HrevhrTmLgxiHB9+HRzEZHkyOm638i5wEwq8K5ZzSiMi7nV44gomzv\nd9MPAapoGe1LKICPedwBvIbHUjOZyq8hYYS1gFKCpFWunyKuWYAuCcg=\n-----END RSA PRIVATE KEY-----\n"
---
# Source: kubefed/charts/controllermanager/templates/webhook.yaml
# The same comments for ValidatingWebhookConfiguration apply here to
# MutatingWebhookConfiguration.
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutation.core.kubefed.io

webhooks:
- name: kubefedconfigs.core.kubefed.io
  clientConfig:
    service:
      namespace: "kube-federation-system"
      name: kubefed-admission-webhook
      path: /apis/mutation.core.kubefed.io/v1beta1/kubefedconfigs
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHakNDQWdLZ0F3SUJBZ0lRYVBPWndSbWg1d0VuMVNaRzhVWG8rVEFOQmdrcWhraUc5dzBCQVFzRkFEQW4KTVNVd0l3WURWUVFERXh4cmRXSmxabVZrTFdGa2JXbHpjMmx2YmkxM1pXSm9iMjlyTFdOaE1CNFhEVEU1TVRJdwpOekUxTkRNMU5sb1hEVEk1TVRJd05ERTFORE0xTmxvd0p6RWxNQ01HQTFVRUF4TWNhM1ZpWldabFpDMWhaRzFwCmMzTnBiMjR0ZDJWaWFHOXZheTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU9lK1NGYnNKMTNidzFkelhyN29JRktob29xamhOT2F5anVoTi9WQ1lGazRtNVE3NWExdzVVTWRmY3RITHN1Ygp3QytMNEUzWFdIM3RUNk4yQnR0MkZEV0w3NmdTZEErOXZJK0g4MUxNY1kvTmo0SkpoYWJjSkFDdnBCT0RTOVJQCngwVThhSXJsbFREc2U4WmlKRmxMWitPdTUwRlZpdWthTTlLR29UNHB0SncrdXhBcmhUMTIzYkwrR0RQQUw4SXoKaVpWaXg4Sjh3eDJYblZWdzBxalZQUUhNMGMxQTBGSHYyYXBzSEo2bG1Ba3JsZ3VHV1ZtVFJsdFBWYUdUcUIrSwpReXFLQnRnUUpzellJSXRDRkFZN1NrWG8rdE9wU2xYSlVacUw4T3FCd0dmbU5NSVl5N0hzS0pqUEhGeGVva21iCi85eHVHK2tHSHh3QmhKZHdIaUh0ZXQwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFDM0NZdjFPbldrTjhUdmM1UENKRzlOZHJ0eTNLSkM0VlVjOUdzMzF6TVdWdnJCCk5ySjl2cnRKWFNtajZjbVFqdzl6SENKQVk2MXVvU3BaSENHOURhdnF6RnVpeDFjMG5XT1dxQmFuVmh6TUczbGEKZkYxeTRMMXVIU2lVRW1GUEgvclhIK3pXb011ZUpXVDdmMUtDODJYd2pWZlM2bE9SVWo3VG9WS2xPVWk2bXZVMAptcDhRcTNuSEVtbkxuMmVPODIrN3owSWdEYWtqN0VMOEJDMUN3WmIxaENPK2RwWnQ2dGtvTHI3bFJEYjZvRWRUCnRja0UvTkV2eEp2R2lEaXR4bVZnS0MvMXpUcWdUOFdWSGRhTk5kQlVHa05hVWdwbVRXYWpUV2hxaTBnVllGWDEKU2RmdHBNVFh0ZGhmbjRHOXZKU2N2Tys3eUk3b09DSTdMR3RoMWRCcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  rules:
  - operations:
    - CREATE
    apiGroups:
    - core.kubefed.io
    apiVersions:
    - v1beta1
    resources:
    - kubefedconfigs
  failurePolicy: Fail
---
# Source: kubefed/charts/controllermanager/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
# For namespace scoped deployments, create a unique cluster-scoped resource
# using the namespace.
  name: validations.core.kubefed.io

webhooks:
- name: federatedtypeconfigs.core.kubefed.io
  clientConfig:
    service:
      namespace: "kube-federation-system"
      name: kubefed-admission-webhook
      path: /apis/validation.core.kubefed.io/v1beta1/federatedtypeconfigs
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHakNDQWdLZ0F3SUJBZ0lRYVBPWndSbWg1d0VuMVNaRzhVWG8rVEFOQmdrcWhraUc5dzBCQVFzRkFEQW4KTVNVd0l3WURWUVFERXh4cmRXSmxabVZrTFdGa2JXbHpjMmx2YmkxM1pXSm9iMjlyTFdOaE1CNFhEVEU1TVRJdwpOekUxTkRNMU5sb1hEVEk1TVRJd05ERTFORE0xTmxvd0p6RWxNQ01HQTFVRUF4TWNhM1ZpWldabFpDMWhaRzFwCmMzTnBiMjR0ZDJWaWFHOXZheTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU9lK1NGYnNKMTNidzFkelhyN29JRktob29xamhOT2F5anVoTi9WQ1lGazRtNVE3NWExdzVVTWRmY3RITHN1Ygp3QytMNEUzWFdIM3RUNk4yQnR0MkZEV0w3NmdTZEErOXZJK0g4MUxNY1kvTmo0SkpoYWJjSkFDdnBCT0RTOVJQCngwVThhSXJsbFREc2U4WmlKRmxMWitPdTUwRlZpdWthTTlLR29UNHB0SncrdXhBcmhUMTIzYkwrR0RQQUw4SXoKaVpWaXg4Sjh3eDJYblZWdzBxalZQUUhNMGMxQTBGSHYyYXBzSEo2bG1Ba3JsZ3VHV1ZtVFJsdFBWYUdUcUIrSwpReXFLQnRnUUpzellJSXRDRkFZN1NrWG8rdE9wU2xYSlVacUw4T3FCd0dmbU5NSVl5N0hzS0pqUEhGeGVva21iCi85eHVHK2tHSHh3QmhKZHdIaUh0ZXQwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFDM0NZdjFPbldrTjhUdmM1UENKRzlOZHJ0eTNLSkM0VlVjOUdzMzF6TVdWdnJCCk5ySjl2cnRKWFNtajZjbVFqdzl6SENKQVk2MXVvU3BaSENHOURhdnF6RnVpeDFjMG5XT1dxQmFuVmh6TUczbGEKZkYxeTRMMXVIU2lVRW1GUEgvclhIK3pXb011ZUpXVDdmMUtDODJYd2pWZlM2bE9SVWo3VG9WS2xPVWk2bXZVMAptcDhRcTNuSEVtbkxuMmVPODIrN3owSWdEYWtqN0VMOEJDMUN3WmIxaENPK2RwWnQ2dGtvTHI3bFJEYjZvRWRUCnRja0UvTkV2eEp2R2lEaXR4bVZnS0MvMXpUcWdUOFdWSGRhTk5kQlVHa05hVWdwbVRXYWpUV2hxaTBnVllGWDEKU2RmdHBNVFh0ZGhmbjRHOXZKU2N2Tys3eUk3b09DSTdMR3RoMWRCcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - core.kubefed.io
    apiVersions:
    - v1beta1
    resources:
    - federatedtypeconfigs
    - federatedtypeconfigs/status
  failurePolicy: Fail
- name: kubefedclusters.core.kubefed.io
  clientConfig:
    service:
      namespace: "kube-federation-system"
      name: kubefed-admission-webhook
      path: /apis/validation.core.kubefed.io/v1beta1/kubefedclusters
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHakNDQWdLZ0F3SUJBZ0lRYVBPWndSbWg1d0VuMVNaRzhVWG8rVEFOQmdrcWhraUc5dzBCQVFzRkFEQW4KTVNVd0l3WURWUVFERXh4cmRXSmxabVZrTFdGa2JXbHpjMmx2YmkxM1pXSm9iMjlyTFdOaE1CNFhEVEU1TVRJdwpOekUxTkRNMU5sb1hEVEk1TVRJd05ERTFORE0xTmxvd0p6RWxNQ01HQTFVRUF4TWNhM1ZpWldabFpDMWhaRzFwCmMzTnBiMjR0ZDJWaWFHOXZheTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU9lK1NGYnNKMTNidzFkelhyN29JRktob29xamhOT2F5anVoTi9WQ1lGazRtNVE3NWExdzVVTWRmY3RITHN1Ygp3QytMNEUzWFdIM3RUNk4yQnR0MkZEV0w3NmdTZEErOXZJK0g4MUxNY1kvTmo0SkpoYWJjSkFDdnBCT0RTOVJQCngwVThhSXJsbFREc2U4WmlKRmxMWitPdTUwRlZpdWthTTlLR29UNHB0SncrdXhBcmhUMTIzYkwrR0RQQUw4SXoKaVpWaXg4Sjh3eDJYblZWdzBxalZQUUhNMGMxQTBGSHYyYXBzSEo2bG1Ba3JsZ3VHV1ZtVFJsdFBWYUdUcUIrSwpReXFLQnRnUUpzellJSXRDRkFZN1NrWG8rdE9wU2xYSlVacUw4T3FCd0dmbU5NSVl5N0hzS0pqUEhGeGVva21iCi85eHVHK2tHSHh3QmhKZHdIaUh0ZXQwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFDM0NZdjFPbldrTjhUdmM1UENKRzlOZHJ0eTNLSkM0VlVjOUdzMzF6TVdWdnJCCk5ySjl2cnRKWFNtajZjbVFqdzl6SENKQVk2MXVvU3BaSENHOURhdnF6RnVpeDFjMG5XT1dxQmFuVmh6TUczbGEKZkYxeTRMMXVIU2lVRW1GUEgvclhIK3pXb011ZUpXVDdmMUtDODJYd2pWZlM2bE9SVWo3VG9WS2xPVWk2bXZVMAptcDhRcTNuSEVtbkxuMmVPODIrN3owSWdEYWtqN0VMOEJDMUN3WmIxaENPK2RwWnQ2dGtvTHI3bFJEYjZvRWRUCnRja0UvTkV2eEp2R2lEaXR4bVZnS0MvMXpUcWdUOFdWSGRhTk5kQlVHa05hVWdwbVRXYWpUV2hxaTBnVllGWDEKU2RmdHBNVFh0ZGhmbjRHOXZKU2N2Tys3eUk3b09DSTdMR3RoMWRCcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - core.kubefed.io
    apiVersions:
    - v1beta1
    resources:
    - kubefedclusters
    - kubefedclusters/status
  failurePolicy: Fail
- name: kubefedconfigs.core.kubefed.io
  clientConfig:
    service:
      namespace: "kube-federation-system"
      name: kubefed-admission-webhook
      path: /apis/validation.core.kubefed.io/v1beta1/kubefedconfigs
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHakNDQWdLZ0F3SUJBZ0lRYVBPWndSbWg1d0VuMVNaRzhVWG8rVEFOQmdrcWhraUc5dzBCQVFzRkFEQW4KTVNVd0l3WURWUVFERXh4cmRXSmxabVZrTFdGa2JXbHpjMmx2YmkxM1pXSm9iMjlyTFdOaE1CNFhEVEU1TVRJdwpOekUxTkRNMU5sb1hEVEk1TVRJd05ERTFORE0xTmxvd0p6RWxNQ01HQTFVRUF4TWNhM1ZpWldabFpDMWhaRzFwCmMzTnBiMjR0ZDJWaWFHOXZheTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU9lK1NGYnNKMTNidzFkelhyN29JRktob29xamhOT2F5anVoTi9WQ1lGazRtNVE3NWExdzVVTWRmY3RITHN1Ygp3QytMNEUzWFdIM3RUNk4yQnR0MkZEV0w3NmdTZEErOXZJK0g4MUxNY1kvTmo0SkpoYWJjSkFDdnBCT0RTOVJQCngwVThhSXJsbFREc2U4WmlKRmxMWitPdTUwRlZpdWthTTlLR29UNHB0SncrdXhBcmhUMTIzYkwrR0RQQUw4SXoKaVpWaXg4Sjh3eDJYblZWdzBxalZQUUhNMGMxQTBGSHYyYXBzSEo2bG1Ba3JsZ3VHV1ZtVFJsdFBWYUdUcUIrSwpReXFLQnRnUUpzellJSXRDRkFZN1NrWG8rdE9wU2xYSlVacUw4T3FCd0dmbU5NSVl5N0hzS0pqUEhGeGVva21iCi85eHVHK2tHSHh3QmhKZHdIaUh0ZXQwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFDM0NZdjFPbldrTjhUdmM1UENKRzlOZHJ0eTNLSkM0VlVjOUdzMzF6TVdWdnJCCk5ySjl2cnRKWFNtajZjbVFqdzl6SENKQVk2MXVvU3BaSENHOURhdnF6RnVpeDFjMG5XT1dxQmFuVmh6TUczbGEKZkYxeTRMMXVIU2lVRW1GUEgvclhIK3pXb011ZUpXVDdmMUtDODJYd2pWZlM2bE9SVWo3VG9WS2xPVWk2bXZVMAptcDhRcTNuSEVtbkxuMmVPODIrN3owSWdEYWtqN0VMOEJDMUN3WmIxaENPK2RwWnQ2dGtvTHI3bFJEYjZvRWRUCnRja0UvTkV2eEp2R2lEaXR4bVZnS0MvMXpUcWdUOFdWSGRhTk5kQlVHa05hVWdwbVRXYWpUV2hxaTBnVllGWDEKU2RmdHBNVFh0ZGhmbjRHOXZKU2N2Tys3eUk3b09DSTdMR3RoMWRCcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - core.kubefed.io
    apiVersions:
    - v1beta1
    resources:
    - kubefedconfigs
  failurePolicy: Fail
