apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: db
        image: postgres:12-alpine
        env:
        - name: POSTGRES_USER
          value: chatalk
        - name: POSTGRES_PASSWORD
          value: chatalk
