apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534
      containers:
      - name: ping
        image: registry.chatalk.fr/ping:master
        imagePullPolicy: Always
        env:
          - name: NATS_URL
            valueFrom:
              configMapKeyRef:
                name: svc-config
                key: NATS_URL
          - name: NATS_CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: svc-config
                key: NATS_CLUSTER_ID
