apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx-ingress-controller
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 1500m
              memory: 1500Mi
