apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: login
        image: registry.chatalk.fr/login:master
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: NATS_CLUSTER_ID
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_HOST
        - name: DB_HOST_READ
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_HOST_READ
        - name: DB_DB
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_PASS
        - name: DB_MODE
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_MODE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: JWT_SECRET
