- name: setup multiple authorized keys for user {{ ansible_user }}
  authorized_key:
    user: '{{ ansible_user }}'
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/ludovicm67
    - public_keys/ludovicm67-ipad
    - public_keys/gvetrivel
  tags:
    - first-run

- name: sudo without password for user {{ ansible_user }}
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  tags:
    - first-run

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 1500 # 15 minutes
  tags:
    - first-run

- name: upgrade packages
  apt:
    upgrade: yes
  tags:
    - first-run

- name: install required packages
  apt:
    pkg:
      - aptitude
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - gnupg-agent
      - htop
      - software-properties-common
      - vim
      - zsh
  tags:
    - first-run

- name: set zsh as default shell for user {{ ansible_user }}
  user:
    name: '{{ ansible_user }}'
    shell: /usr/bin/zsh
  tags:
    - first-run

- name: set zsh as default shell for user root
  user:
    name: root
    shell: /usr/bin/zsh
  tags:
    - first-run

- name: copy zsh config files
  copy:
    src: '{{ item.src }}'
    dest: '/etc/zsh/{{ item.path }}'
  with_filetree: zsh/
  when: item.state == 'file'
  tags:
    - first-run

- name: create mount directory for pgdata PV
  file:
    path: /srv/store/pgdata
    state: directory

- name: mount directory for pgdata PV
  mount:
    path: /srv/data/pgdata
    src: /srv/store/pgdata
    state: mounted
    opts: bind
    fstype: none
