apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: monitoring
  name: grafana
spec:
  tls:
  - hosts:
    - grafana-cluster2.chatalk.fr
    secretName: chatalk-cert
  rules:
  - host: grafana-cluster2.chatalk.fr
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
