---
# run all common tasks
- hosts: all
  become: yes
  roles:
    - common

# import Kubespray playbook
# - import_playbook: kubespray/cluster.yml

# run tasks for dumas
- hosts: dumas
  become: yes
  roles:
    - dumas
