---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart registry
  systemd:
    name: registry
    state: restarted

- name: restart minio
  systemd:
    name: minio
    state: restarted
