apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-init
spec:
  template:
    spec:
      serviceAccount: stolon
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: stolonctl
        image: sandhose/stolon:latest
        volumeMounts:
        - name: stolon-config-volume
          mountPath: /etc/stolon/init.json
          subPath: init.json
        imagePullPolicy: Always
        command:
        - "stolonctl"
        - "init"
        - "--cluster-name=chatalk"
        - "--store-backend=kubernetes"
        - "--kube-resource-kind=configmap"
        - "--yes"
        - "--file=/etc/stolon/init.json"
        env:
        - name: STKEEPER_CLUSTER_NAME
          value: chatalk
        - name: STKEEPER_STORE_BACKEND
          value: "kubernetes"
        - name: STKEEPER_KUBE_RESOURCE_KIND
          value: "configmap"
      restartPolicy: OnFailure
      volumes:
      - name: stolon-config-volume
        configMap:
          name: stolon-config
