apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stolon

commonLabels:
  app.kubernetes.io/name: stolon

bases:
- init/
- keeper/
- sentinel/
- proxy/

resources:
- namespace.yaml
- stolon-sa.yaml
- stolon-role.yaml
- stolon-rb.yaml

secretGenerator:
- name: stolon
  literals:
  - su-password=aix7eePeH9ooqui6ShaiT7eiphaeTee2isahg2ahwibiwoh8Ailequ2jeiceeSho
  - repl-password=quogh5UeLal9gookeiGie0Hahch6Gaju7Ee7caechooshau9nees0thuwuf8aa6u
