apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: chatalk

namespace: chatalk

bases:
- conv_creation
- conv_manag
- db-migrations
- entrypoint
- login
- msg_sender
- ping
- register
- send-info
- ui

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: svc-config
  literals:
  - NATS_URL=nats://nats:4222
  - NATS_CLUSTER_ID=stan
  - DB_HOST=dbmaster.chatalk.fr
  - DB_HOST_READ=stolon-proxy.stolon.svc
  - DB_DB=chatalk
  - DB_USER=chatalk
  - DB_PASS=ieceetiothux6aechieBohvoozaezo1zaetequahShuw6faePeng4shaem3raece
  - DB_MODE=disable
  - JWT_SECRET=ieRe9Pohyah3uacheJaeTho8
