apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: chatalk

namespace: chatalk

bases:
- db
- conv_creation
- conv_manag
- db-migrations
- entrypoint
- fake-ui
- login
- msg_sender
- ping
- register
- send-info
- ui
