apiVersion: v1
data:
  prometheus-additional.yaml: LSAiaG9ub3JfbGFiZWxzIjogdHJ1ZQogICJqb2JfbmFtZSI6ICJmZWRlcmF0ZSIKICAibWV0cmljc19wYXRoIjogIi9mZWRlcmF0ZSIKICAicGFyYW1zIjoKICAgICJtYXRjaFtdIjoKICAgIC0gIntqb2I9XCJzdGFuLXN2Y1wifSIKICAic2NyYXBlX2ludGVydmFsIjogIjE1cyIKICAic3RhdGljX2NvbmZpZ3MiOgogIC0gInRhcmdldHMiOgogICAgLSAiY2x1c3RlcjIuY2hhdGFsay5mcjo5MDkwIg==
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
type: Opaque
