apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-info
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534
      containers:
      - name: send-info
        image: registry.chatalk.fr/send-info:master
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: NATS_CLUSTER_ID
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_HOST
        - name: DB_DB
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_PASS
        - name: DB_MODE
          valueFrom:
            configMapKeyRef:
              name: svc-config
              key: DB_MODE
