apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: entrypoint
        image: registry.chatalk.fr/entrypoint:master
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          value: nats://nats:4222
        - name: NATS_CLUSTER_ID
          value: stan
