apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: chatalk

namespace: chatalk

bases:
- db
- db-migrations
- bus
- entrypoint
- fake-ui
- ping
- register
