apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  template:
    spec:
      containers:
      - name: postgres-operator
        image: registry.opensource.zalan.do/acid/postgres-operator:v1.2.0-15-gbb855fd-dirty
