apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config: |
    address-pools:
    - name: public
      protocol: layer2
      addresses:
      - 130.79.86.28/32 # Public IP address range
